#!/usr/bin/env bash

# checkfiles - See if all listed files are present in a folder
#
# D Provine, 6 March 2021

# This sets up some error checking and basic help
set -o errexit   # stop script when an error occurs
set -o pipefail  # stop if a pipe fails
set -o nounset   # stop if an unset variable is accessed

# uncomment the next line to turn on debugging
# set -o xtrace


if (( $# != 2 )); then
    printf "Usage: %s filename foldername\n"
    exit 1
fi

printf "Checking folder %s against file list %s\n" $2 $1


